-- 코드를 입력하세요
SELECT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID=C.CAR_ID
WHERE CAR_TYPE='세단' AND START_DATE LIKE '2022-10-%'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;